### ISSUE TITLE
Azure VM Issue

### ISSUE THREAD

**Issue by jamessdixon** [mbraceproject/MBrace.Legacy#11]
I am following the tutorial found here(http://www.m-brace.net/azure-tutorial.html) and I am getting caught up on the last piece of the code.

I have 5 VMs stood up that are giving back a successful ping:
#load "../../packages/MBrace.Runtime.0.5.13-alpha/bootstrap.fsx" 

open Nessos.MBrace
open Nessos.MBrace.Client

let nodes =
    [
        MBraceNode.Connect("10.0.1.4", 2675)
        MBraceNode.Connect("10.0.1.6", 2675)
        MBraceNode.Connect("10.0.1.5", 2675)
        MBraceNode.Connect("10.0.1.7", 2675)
        MBraceNode.Connect("10.0.1.8", 2675)
    ]

nodes |> List.iter(fun n -> printfn "Node %A"(n.Ping().ToString()))

Returns
[Loading F:\Git\MBrace.Demos\packages\MBrace.Runtime.0.5.13-alpha\bootstrap.fsx]

namespace FSI_0002

Node "00:00:00.0731441"
Node "00:00:00.0527995"
Node "00:00:00.0563894"
Node "00:00:00.0730258"
Node "00:00:00.0530820"

val nodes : Nessos.MBrace.Client.MBraceNode list =
  [mbrace://10.0.1.4:2675/; mbrace://10.0.1.6:2675/; mbrace://10.0.1.5:2675/;
   mbrace://10.0.1.7:2675/; mbrace://10.0.1.8:2675/]
val it : unit = ()

When I attempt to use the local file system as the store like this:

#I "../../packages/MBrace.Azure.0.5.13-alpha/lib/net45/"
#r "MBrace.Azure.dll"

open Nessos.MBrace.Azure
open Nessos.MBrace.Store

let fileSystemStore = FileSystemStore.Create @"C:\MBrace"
MBraceSettings.DefaultStore <- fileSystemStore
let runtime = MBrace.Boot nodes

runtime.Run <@ cloud { return 42 } @>

I get this result and exception:
val fileSystemStore : FileSystemStore =
  {Name = "FileSystemStore"; Id = "file://Dixon-PC/C:/MBrace";}

> 
val it : unit = ()
> 
Nessos.Thespian.MessageHandlingException: Remote Actor threw exception while handling message ---> Nessos.MBrace.SystemCorruptedException: Unexpected exception occurred. ---> System.InvalidOperationException: Attempting to boot with incompatible store configuration 'Nessos.MBrace.Store.FileSystemStore, MBrace.Store, Version=0.5.13.0, Culture=neutral, PublicKeyToken=null'
   at Nessos.MBrace.Runtime.Definitions.MBraceNode.storeActivationProtocol@125.Invoke(Unit unitVar) in C:\dev\github-repositories\mbrace\src\MBrace.Runtime.Cluster\MBraceNode.fs:line 134
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@813.Invoke(AsyncParams`1 args)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at <StartupCode$FSI_0007>.$FSI_0007.main@() in F:\Git\MBrace.Demos\Demo.Scripts\Runtime\azure.fsx:line 34
Stopped due to error

Also, when I attempt to point to my Azure Blob Storage, like this:

let accountName = "chickensoftware"
let accountKey = "/Y6Q1PFKNWCr+RVGdj2pTJY3LeoOwbVNGugeaDWUIN0aqQ+gaDscaZW7TgpuTCxJ6O12QMoU5ZWxTsiPEBhcaw=="
let azureStore = AzureStore.Create(accountName = accountName, accountKey = accountKey)
MBraceSettings.DefaultStore <- azureStore
let runtime = MBrace.Boot nodes

I get this:
![capture](https://cloud.githubusercontent.com/assets/1394644/6234977/e43c07d4-b6ac-11e4-89ba-4bbb146aaa08.PNG)

val runtime : MBraceRuntime

But when I run the last line:
runtime.Run <@ cloud { return 42 } @>

I get this:
Binding session to 'F:\Git\MBrace.Demos\packages\MBrace.Runtime.0.5.13-alpha\tools/MBrace.Core.dll'...
System.TimeoutException: Waiting for the reply has timed-out.
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at <StartupCode$FSI_0006>.$FSI_0006.main@()
Stopped due to error

Can you give me some help?

**Comment by eiriktsarpalis** [comment]
Hi Jamie,

As regards the first error message, this happens because FileSystemStore can only be used if its path is visible by all nodes in the cluster. I am however perplexed by the error message you are getting. Does this occur at `MBrace.Boot` or during `runtime.Run`?

As regards the seconds error, could you try doing the following?
```
runtime.CreateProcess <@ cloud { return 42 } @>
```

**Comment by jamessdixon** [comment]
Thanks for answering this!
File system error throws at MBrace.Boot

second error:
runtime.CreateProcess <@ cloud { return 42 } @>

Throws same:
Binding session to 'F:\Git\MBrace.Demos\packages\MBrace.Runtime.0.5.13-alpha\tools/MBrace.Core.dll'...
System.TimeoutException: Waiting for the reply has timed-out.


Is it a firewall issue?  I did have to open port 2675 on each of the azure VMs

**Comment by eiriktsarpalis** [comment]
Strange... Probably not a firewall issue, it wouldn't have been in the position to boot in the first place.

What about `runtime.ShowInfo()` or `runtime.ShowProcessInfo()`?

**Comment by jamessdixon** [comment]
ShowInfo() gives this:
 Host      Port  Role    Location  Connection String       
 ----      ----  ----    --------  -----------------       
 10.0.1.4  2675  Master  Remote    mbrace://10.0.1.4:2675/ 
 10.0.1.5  2675  Slave   Remote    mbrace://10.0.1.5:2675/ 
 10.0.1.6  2675  Slave   Remote    mbrace://10.0.1.6:2675/ 
 10.0.1.7  2675  Slave   Remote    mbrace://10.0.1.7:2675/ 
 10.0.1.8  2675  Slave   Remote    mbrace://10.0.1.8:2675/ 

ShowProcessInfo() gives this
Name  Process Id  Status  #Workers  #Tasks  Start Time  Execution Time  Result Type 
 ----  ----------  ------  --------  ------  ----------  --------------  ----------- 

val it : unit = ()

**Comment by eiriktsarpalis** [comment]
Could I have the logs for the worker nodes during the timeout exception?

**Comment by jamessdixon** [comment]
Sure -> where are they located?  Do I have to enable logging in the app.config?

**Comment by eiriktsarpalis** [comment]
Does `MBraceSettings.DefaultTimeout` property to a larger value solve the problem?
